services:
  - type: web
    name: rag-service
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      # Add any other settings from your .env file
